version: "3.8"

services:
  app:
    container_name: app
    build: ./
    command: ./cmd/run
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=root
  db:
    container_name: db
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - "5436:5432"